services:
  applinkdin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: applinkdin-dashboard
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4000:4000"
    environment:
      APPLINKDIN_API_PORT: 4000
    env_file:
      - ./.env
    restart: unless-stopped
